### ISSUE TITLE
evaluate http2 implementations

### ISSUE THREAD

**Issue by AdrianRossouw** [GraftJS/graft#22]
Graft is built atop a protocol called libchan, which used certain properties of SPDY to be able to provide features similar to Go's channels over the network.

Since SPDY has been killed, and all work is going towards HTTP2, it's kind of put the upstream protocol in flux. I mean, the stuff that's there still works, and works today... but there is some settling left to be done in the eco system.

To work past this on our side, we need to find / help build a mature http2 implementation for node.js.

**Comment by mcollina** [comment]
I'm more for moving out of libchan, forget HTTP2 and SPDY and just use our own binary stream format.
Similar concepts, but with an easier implementation. Consider the fact that we need that anyway for websockets.

I'm kind of working on a new concept, I will let you know when it's done.

**Comment by AdrianRossouw** [comment]
i was thinking that too. it seemed like a shame to have to install node-spdy to install graft.

**Comment by AdrianRossouw** [comment]
so i'm going to mark this as wont-fix.
